site_name: Documentação

nav:
  - Apresentação do Projeto: "index.md"
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Testes: 
    - Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
    - Testes de Integração:
      - Menu de Navegação: "documento-plano-testes/testes_integracao/funcionalidades_gerais/menu_navegacao.md"
      - Tela de Demandas do Admin: "documento-plano-testes/testes_integracao/tela_demanda_adm/integracao_formularios_demanda.md"
      - Tela de Funcionários do Admin: "documento-plano-testes/testes_integracao/tela_funcionarios_adm/integracao_formularios_funcionario.md"
      - Tela de Produtos do Admin: "documento-plano-testes/testes_integracao/tela_produto_adm/integracao_formularios_produtos.md"
    - Testes Manuais:
      - Tela de Login: "documento-plano-testes/testes_manuais/tela_de_login/funcionalidades_gerais.md"
      - Menu de Navegação: "documento-plano-testes/testes_manuais/menu_de_naveg/funcionalidades_gerais.md"
      - Tela de Demandas do Admin:
        - Funcionalidade Gerais: "documento-plano-testes/testes_manuais/tela_demanda_adm/crud.md"
        - Importação da Planilha: "documento-plano-testes/testes_manuais/tela_demanda_adm/importacao_planilha.md"
      - Tela de Desempenho da Loja: "documento-plano-testes/testes_manuais/tela_desemp_loja_adm/funcionalidades_gerais.md"
      - Tela de Funcionários do Admin: "documento-plano-testes/testes_manuais/tela_funcionarios_adm/crud.md"
      - Tela de Produtos: "documento-plano-testes/testes_manuais/tela_produto_adm/crud.md"
    - Testes Unitários:
      - Tela de Login: "documento-plano-testes/testes_unitarios/tela_de_login/funcionalidades_gerais.md"
      - Tela de Demandas do Admin:
        - Funcionalidade Gerais: "documento-plano-testes/testes_unitarios/tela_demanda_adm/crud.md"
        - Importação da Planilha: "documento-plano-testes/testes_unitarios/tela_demanda_adm/planilha.md"
      - Tela de Desempenho dos Funcionários: "documento-plano-testes/testes_unitarios/tela_desemp_loja_adm/funcionalidades_gerais.md"
      - Tela de Desempenho da Loja: "documento-plano-testes/testes_unitarios/tela_desemp_loja_adm/funcionalidades_gerais.md"
      - Tela de Funcionários do Admin: "documento-plano-testes/testes_unitarios/tela_funcionarios_adm/crud.md"
      - Tela de Produtos: "documento-plano-testes/testes_unitarios/tela_produto_adm/crud.md"
  - Atas de Reunião:
    - Ata 21/11: "atas-reuniao/ata-reuniao-21-11.md"
    - Ata 24/11: "atas-reuniao/ata-reuniao-24-11.md"
    - Ata 04/12: "atas-reuniao/ata-reuniao-04-12.md"
    - Ata 09/12: "atas-reuniao/ata-reuniao-09-12.md"
    - Ata 13/12: "atas-reuniao/ata-reuniao-13-12.md"
    - Ata 15/12: "atas-reuniao/ata-reuniao-15-12.md"
    - Ata 16/12: "atas-reuniao/ata-reuniao-16-12.md"
    - Ata 18/12: "atas-reuniao/ata-reuniao-18-12.md"
    - Ata 06/01: "atas-reuniao/ata-reuniao-06-01.md"
    - Ata 08/01: "atas-reuniao/ata-reuniao-08-01.md"
    - Ata 13/01: "atas-reuniao/ata-reuniao-13-01.md"
    - Ata 15/01: "atas-reuniao/ata-reuniao-15-01.md"
    - Ata 27/01: "atas-reuniao/ata-reuniao-27-01.md"
    - Ata 29/01: "atas-reuniao/ata-reuniao-29-01.md"
    - Ata 31/01: "atas-reuniao/ata-reuniao-31-01.md"
    - Ata 05/02: "atas-reuniao/ata-reuniao-05-02.md"

theme:
  name: material