site_name: Documentação

nav:
  - Apresentação do Projeto: "index.md"
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - Ata 21/11: "atas-reuniao/ata-reuniao-21-11.md"
    - Ata 24/11: "atas-reuniao/ata-reuniao-24-11.md"
    - Ata 04/12: "atas-reuniao/ata-reuniao-04-12.md"
    - Ata 09/12: "atas-reuniao/ata-reuniao-09-12.md"
    - Ata 13/12: "atas-reuniao/ata-reuniao-13-12.md"
    - Ata 15/12: "atas-reuniao/ata-reuniao-15-12.md"
    - Ata 16/12: "atas-reuniao/ata-reuniao-16-12.md"
    - Ata 18/12: "atas-reuniao/ata-reuniao-18-12.md"
    - Ata 06/01: "atas-reuniao/ata-reuniao-06-01.md"

theme:
  name: material