site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - Ata 21/11: "atas-reuniao/ata-reuniao-21-11.md"

theme:
  name: material